site_name: Nuclei Studio Supply Documents
docs_dir: docs
repo_url: https://github.com/Nuclei-Software/nuclei-studio
edit_uri: blob/main/
copyright: All rights reserved
nav:
    - Home: README.md
    - 1-cannot-setup-guestmemory.md
    - 2-qemu-glib-gio-unexpectedly.md
    - 3-print_memor_usage_in_ide.md
    - 4-use_pre_build_or_post_build.md
    - 5-update_npk_to_support_nucleistudio_202310.md
    - 6-gcc13_gen_rvv_instructions_when_rvv_enabled.md
    - 7-update_nucleistudio_202310_to_fixed_version.md
    - 8-openocd_202310_flashloader_flaws.md
    - 9-modify_the_cproject_file_to_change_the_project_to_gcc13.md
    - 10-compiling_projects_with_headless_in_nuclei_studio.md
    - 11-openocd_reported_error_not_known_as_fespi_capable.md
    - 12-nucleisdk-0.5.0-dhrystone-score-lower-than-expected-in-IDE.md
    - 13-error_could_not_find_an_available_hardware_trigger.md
    - 14-cannot_find_-lncrt_balanced_no_such_file_or_directory.md
    - 15-unsatisfiedLinkError_of_swt-win32-4965r8_dll_on_windows7.md
    - 16-incomplete_data_output_when_using_profiling_function.md
    - 17-an_example_to_demonstrate_the_use_of_profiling_and_code_coverage.md
    - 18-demonstrate_NICE_VNICE_acceleration_of_the_Nuclei_Model_through_profiling.md
    - 19-rapid_verification_of_NICE_VNICE_acceleration_with_Nuclei_Model_and_NICE_Wizard.md
    - 20-quick_downloads_using_flash_programming.md
    - 21-livewatch_for_monitoring_variables.md
    - 22-example_for_adding_new_intructions_in_llvm.md
    - 23-nuclei_debug_map_register_analyze.md
exclude_docs: |
    0-*.md
theme:
   name: readthedocs
   highlightjs: true
   locale: zh
plugins:
  - mkpdfs:
      author: "Nuclei Software"
      company: "Nuclei System Technology"
      toc_title: Table of contents
      output_path: pdf/nuclei_studio_supply.pdf
      design: report.css
markdown_extensions:
  - toc:
      permalink: true
  - github-callouts
  - codehilite
  - pymdownx.magiclink
# https://github.com/mkdocs/mkdocs-bootswatch/issues/65#issuecomment-1030505626
extra_css:
  - extra.css
